### ISSUE TITLE
Direction button on nextion not updating

### ISSUE THREAD

**Issue by Rosscoetrain** [normhal/DCCppEX-Nextion-Controller#1]
DCCppEX-Nextion-Controller V1.7.5
Nextion 3.5" basic
ESP32

Using a rotary encoder on pressing the direction switch the direction is changed correctly (can be seen in the serial monitor).

However the button on the nextion throttle screen is not changed.

Throttle slider updates correctly.

**Comment by normhal** [comment]
Thanks for the info:-) Version 1.7.6b is ready for upload - I'll check it out! Good to have another user!:-)

**Comment by normhal** [comment]
Thanks for highlighting! I've just uploaded version 1.7.7 together with
matching TFT files...

**Comment by Rosscoetrain** [comment]
Works fine now.
